name: 01 - Building Blocks
on: push
jobs:
    echo-hello:
        runs-on: ubnuntu-latest
        steps:
            - name: Say Hello  
              run: echo "Hello, world!"
    echo-goodbye:
        runs-on: ubuntu-latest
        steps:
            - name: Success Step
              run: |
                echo "This step Successes"
                exit 0
            - name: Say Goodbye
              run: echo "Goodbye"